### ISSUE TITLE
Missing Dockerfile

### ISSUE THREAD

**Issue by Ji-Shao** [ionos-cloud/dim#79]
I love to test this app via docker but it seems to me Dockerfile was missing.

**Comment by miesi** [comment]
Sorry, you are right.

I've just uploaded a qcow2 image with everything inside needed to test DIM. A Quickstart/Tutorial (wip) can be found here: https://github.com/miesi/dim/blob/master/QUICKSTART.md

**Comment by miesi-ionos** [comment]
Should be implemented now thanks to @parsa97
